"use client";

import Link from "next/link";
import "../css/style.css";
import { usePathname } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body>
        <ul className="navbar">
          <h1>
            <Link href="#">NextJS Project</Link>
          </h1>
          <div className="navigation">
            <li>
              <Link href="/" className={pathName === "/" ? "nav-active" : ""}>
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/dashboard"
                className={pathName === "/dashboard" ? "nav-active" : ""}
              >
                Dashboard
              </Link>
            </li>
            <li>
              <Link
                href="/settings"
                className={pathName === "/settings" ? "nav-active" : ""}
              >
                Settings
              </Link>
            </li>
            <li>
              <Link
                href="/find"
                className={pathName === "/find" ? "nav-active" : ""}
              >
                find
              </Link>
            </li>
          </div>
        </ul>
        {children}
      </body>
    </html>
  );
}
