import Navbar from "../components/Navbar";
import "../css/globals.css";

export function generateMetadata() {
  return {
    title: "alok.js",
    description: "Generated by Next.js",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
